stages:
  - stage_test
  - stage_build_python
  - stage_build_docker
  - stage_build_documentation
  - stage_push_python
  - stage_push_docker
  - stage_push_documentation
  - stage_deploy

# Docker

job_docker_build:
  stage: stage_build_docker
  image: docker:latest
  services:
    - docker:dind
    - postgres:9.6-alpine
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f docker/Dockerfile .
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - SERVICE_POSTGRES_IP=$(cat /etc/hosts | awk '{if ($2 == "postgres") print $1;}')
    - docker run --rm --add-host="postgres:$SERVICE_POSTGRES_IP" -e MAYAN_DATABASES="{'default':{'ENGINE':'django.db.backends.postgresql_psycopg2','NAME':'mayan_edms','USER':'postgres','PASSWORD':'postgres','HOST':'postgres'}}" "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" run_tests
    - docker push "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - docker logout
  only:
    - releases/all
    - releases/all_minor
    - releases/docker
  tags:
    - postgres
  variables:
    POSTGRES_DB: "mayan_edms"
    POSTGRES_PASSWORD: "postgres"

job_docker_push:
  stage: stage_push_docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - PYTHON_BIN=/usr/bin/python3
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - docker pull "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:"$DOCKER_VERSION"
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:latest
    - VERSION_SCRIPT_BIN=contrib/scripts/version.py
    - MAJOR_VERSION=$($PYTHON_BIN $VERSION_SCRIPT_BIN $DOCKER_VERSION major);
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:"$MAJOR_VERSION"
    - MINOR_VERSION=$($PYTHON_BIN $VERSION_SCRIPT_BIN $DOCKER_VERSION minor);
    - if [ -z MINOR_VERSION ]; then docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:"$MINOR_VERSION";fi
    - docker logout
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" https://registry-1.docker.io
    - docker push registry-1.docker.io/mayanedms/mayanedms:"$DOCKER_VERSION"
    - docker push registry-1.docker.io/mayanedms/mayanedms:latest
    - docker push registry-1.docker.io/mayanedms/mayanedms:"$MAJOR_VERSION"
    - if [ -z MINOR_VERSION ]; then docker push registry-1.docker.io/mayanedms/mayanedms:"$MINOR_VERSION";fi
  only:
    - releases/all
    - releases/docker

job_docker_push_minor:
  stage: stage_push_docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - PYTHON_BIN=/usr/bin/python3
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - docker pull "$CI_REGISTRY_IMAGE:$DOCKER_VERSION"
    - docker tag "$CI_REGISTRY_IMAGE:$DOCKER_VERSION" registry-1.docker.io/mayanedms/mayanedms:"$DOCKER_VERSION"
    - docker logout
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" https://registry-1.docker.io
    - docker push registry-1.docker.io/mayanedms/mayanedms:"$DOCKER_VERSION"
  only:
    - releases/all_minor
    - releases/docker

job_docker_nightly:
  stage: stage_build_docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker logout
  only:
    - nightly
    - staging

# Documentation

job_documentation_build:
  stage: stage_build_documentation
  image: debian:10.7-slim
  artifacts:
    expire_in: 2 hr
    paths:
    - docs
  before_script:
    - apt-get -qq update
    - apt-get install -qq enchant make python3-venv python3-dev
    - python3 -m venv venv
    - . venv/bin/activate
  script:
    - pip install --requirement requirements/documentation.txt
    - cd docs
    - make html
  only:
    - releases/all
    - releases/documentation

job_documentation_push:
  stage: stage_push_documentation
  image: debian:10.7-slim
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DOCUMENTATION_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'which ssh-agent || ( apt-get update --yes && apt-get install -qq openssh-client rsync --yes )'
    - eval $(ssh-agent -s)
    - echo "$DOCUMENTATION_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - ssh mayandocs@docs.mayan-edms.com "rm -Rf /home/rosarior/webapps/mayan_docs/*"
    - rsync -avzP --progress -e ssh docs/_build/html/* mayandocs@docs.mayan-edms.com:/home/rosarior/webapps/mayan_docs
  only:
    - releases/all
    - releases/documentation

# Python

job_build_python:
  stage: stage_build_python
  image: debian:10.7-slim
  artifacts:
    expire_in: 2 hr
    paths:
    - dist
  before_script:
    - apt-get -qq update
    - apt-get install -qq make python3-venv python3-dev
    - python3 -m venv venv
    - . venv/bin/activate
  script:
    - pip install --requirement requirements/build.txt
    - make python-wheel
  only:
    - releases/all
    - releases/all_minor
    - releases/python

job_push_python:
  stage: stage_push_python
  image: debian:10.7-slim
  before_script:
    - apt-get -qq update
    - apt-get install -qq make python3-venv python3-dev
    - python3 -m venv venv
    - . venv/bin/activate
  script:
    - pip install --requirement requirements/build.txt
    - echo "$PYPIRC" > ~/.pypirc
    - twine upload dist/* -r pypi
  only:
    - releases/all
    - releases/all_minor
    - releases/python

# Test upgrade from the latest public version to the local version

.job_test_upgrade_base: &job_test_upgrade_base
  stage: stage_test
  image: debian:10.7-slim
  cache:
    paths:
      - ~/.cache/pip/
      - /var/cache/apt/archives/
  before_script:
    - set -a && . ./config.env && set +a
    - apt-get -qq update
    - apt-get install -qq curl exiftool gcc ghostscript gnupg1 libjpeg-dev libmagic1 libpng-dev libtiff-dev make poppler-utils python3-venv python3-dev tesseract-ocr
    - python3 -m venv venv
    - . venv/bin/activate
    - DOCKER_VERSION=`cat docker/rootfs/version`
    - pip install "mayan-edms<$DOCKER_VERSION"
    - pip install --requirement requirements/build.txt --requirement requirements/testing-base.txt --requirement requirements/build.txt
    - make python-wheel
  only:
    - releases/all
    - releases/all_minor
    - releases/docker
    - releases/python
    - staging

job_test_upgrade_sqlite:
  <<: *job_test_upgrade_base
  script:
    - . venv/bin/activate
    - mayan-edms.py initialsetup --settings=mayan.settings.testing.gitlab-ci
    - pip install dist/mayan_edms-*.whl
    - mayan-edms.py performupgrade --settings=mayan.settings.testing.gitlab-ci

job_test_upgrade_mysql:
  <<: *job_test_upgrade_base
  variables:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: "mayan_edms"
  services:
    - mysql:5.7
  script:
    - apt-get install -qq default-libmysqlclient-dev default-mysql-client libssl-dev
    - . venv/bin/activate
    - pip install mysqlclient==$PYTHON_MYSQL_VERSION
    - mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD" -e "set global character_set_server=utf8mb4;"
    - mayan-edms.py initialsetup --settings=mayan.settings.testing.gitlab-ci.db_mysql
    - pip install dist/mayan_edms-*.whl
    - mayan-edms.py performupgrade --settings=mayan.settings.testing.gitlab-ci.db_mysql
  tags:
    - mysql

job_test_upgrade_postgres:
  <<: *job_test_upgrade_base
  variables:
    POSTGRES_DB: "mayan_edms"
    POSTGRES_PASSWORD: "postgres"
  services:
    - postgres:9.6-alpine
  script:
    - apt-get install -qq libpq-dev
    - . venv/bin/activate
    - pip install psycopg2==$PYTHON_PSYCOPG2_VERSION
    - mayan-edms.py initialsetup --settings=mayan.settings.testing.gitlab-ci.db_postgres
    - pip install dist/mayan_edms-*.whl
    - mayan-edms.py performupgrade --settings=mayan.settings.testing.gitlab-ci.db_postgres
  tags:
    - postgres

# Run the test suit

.job_test_base: &job_test_base
  stage: stage_test
  image: debian:10.7-slim
  cache:
    paths:
      - ~/.cache/pip/
      - /var/cache/apt/archives/
  before_script:
    - set -a && . ./config.env && set +a
    - echo "deb http://deb.debian.org/debian buster-backports main contrib non-free" >> /etc/apt/sources.list
    - echo "deb-src http://deb.debian.org/debian buster-backports main contrib non-free" >> /etc/apt/sources.list
    - apt-get update
    - apt-get install --yes --no-install-recommends --target-release buster-backports -qq libreoffice-calc-nogui libreoffice-draw-nogui libreoffice-impress-nogui libreoffice-math-nogui libreoffice-writer-nogui
    - apt-get install --yes --no-install-recommends -qq curl exiftool gcc ghostscript gnupg1 graphviz libfuse2 libjpeg-dev libmagic1 libpng-dev libtiff-dev make poppler-utils python3-venv python3-dev sane-utils tesseract-ocr tesseract-ocr-deu
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install wheel
    - pip install --requirement requirements.txt --requirement requirements/testing-base.txt --requirement requirements/build.txt
  only:
    - releases/all
    - releases/docker
    - releases/python
    - staging

job_test_postgres:
  <<: *job_test_base
  variables:
    POSTGRES_DB: "mayan_edms"
    POSTGRES_PASSWORD: "postgres"
  services:
    - postgres:9.6-alpine
  script:
    - apt-get install -qq libpq-dev
    - . venv/bin/activate
    - pip install psycopg2==$PYTHON_PSYCOPG2_VERSION
    - make test-all SETTINGS=mayan.settings.testing.gitlab-ci.db_postgres
    - make test-all-migrations SETTINGS=mayan.settings.testing.gitlab-ci.db_postgres
  tags:
    - postgres

job_test_sqlite:
  <<: *job_test_base
  script:
    - . venv/bin/activate
    - python manage.py test --mayan-apps --settings=mayan.settings.testing.gitlab-ci --skip-migrations
    - make test-all
    - make test-all-migrations

# Deploy

job_deploy_demo:
  environment:
    name: demo
  stage: stage_deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "${DEMO_SSH_KNOWN_HOST}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "${DEMO_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - scp contrib/scripts/install/docker.sh root@$DEMO_IP_ADDRESS:~
    - ssh root@$DEMO_IP_ADDRESS "DELETE_VOLUMES=true ./docker.sh"
  when: manual

job_deploy_staging:
  environment:
    name: staging
  stage: stage_deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "${STAGING_SSH_KNOWN_HOST}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "${STAGING_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - scp contrib/scripts/install/docker.sh root@$STAGING_IP_ADDRESS:~
    - ssh root@$STAGING_IP_ADDRESS "DOCKER_MAYAN_IMAGE=registry.gitlab.com/mayan-edms/mayan-edms:staging ./docker.sh"
  when: manual
