language: python
python:
  - 2.7
env:
  global:
   - TEST_APPS="acls authentication django_gpg document_indexing document_signatures documents dynamic_search folders lock_manager ocr permissions sources tags"
  matrix:
   - DB=mysql
   - DB=postgres
   - DB=sqlite
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev gcc tesseract-ocr tesseract-ocr-deu unpaper ghostscript libjpeg-dev libpng-dev poppler-utils
install:
  - "pip install -r requirements/testing.txt"
  - if [[ $DB == mysql ]]; then pip install -q mysql-python; fi
  - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
before_script:
  - mysql -e 'create database mayan_edms;'
  - psql -c 'create database mayan_edms;' -U postgres
script:
  - if [[ $DB == mysql ]]; then coverage run manage.py test $TEST_APPS --settings=mayan.settings.travis.db_mysql; fi
  - if [[ $DB == postgres ]]; then coverage run manage.py test $TEST_APPS --settings=mayan.settings.travis.db_postgres; fi
  - if [[ $DB == sqlite ]]; then coverage run manage.py test $TEST_APPS --settings=mayan.settings.travis.base; fi
after_success:
  - coveralls
branches:
  only:
    - master
    - development
notifications:
  email:
    recipients:
    - roberto.rosario@mayan-edms.com
    on_success: never
    on_failure: always
