version: '3.7'

networks:
  mayan-bridge:
    driver: bridge

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgresql
      - redis
      # Enable to use RabbitMQ
      #- rabbitmq
    environment: &mayan_env
      # Enable to use RabbitMQ
      # MAYAN_CELERY_BROKER_URL: amqp://mayan:mayanrabbitpass@broker:5672/mayan
      # Disable Redis Broker to use RabbitMQ as Broker
      MAYAN_CELERY_BROKER_URL: redis://redis:6379/1
      MAYAN_CELERY_RESULT_BACKEND: redis://redis:6379/0
      MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'mayan','PASSWORD':'mayandbpass','USER':'mayan','HOST':'postgresql'}}"
    image: mayanedms/mayanedms:3.2.6
    networks:
      - mayan-bridge
    ports:
      - "80:8000"
    restart: unless-stopped
    volumes:
      - /docker-volumes/mayan-edms/media:/var/lib/mayan

  postgresql:
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayandbpass
      POSTGRES_USER: mayan
    image: postgres:9.6
    networks:
      - mayan-bridge
    restart: unless-stopped
    volumes:
      - /docker-volumes/mayan-edms/postgres:/var/lib/postgresql/data

  redis:
    command:
      - redis-server
      - --databases
      - "2"
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - ""
    image: redis:5.0
    networks:
      - mayan-bridge
    restart: unless-stopped

  # Optional services

  # celery_flower:
  #   command:
  #     - run_celery
  #     - flower
  #   depends_on:
  #     - postgresql
  #     - redis
  #     # Enable to use RabbitMQ
  #     # - rabbitmq
  #   environment:
  #     <<: *mayan_env
  #   image: mayanedms/mayanedms:3.2.6
  #   networks:
  #     - mayan-bridge
  #   ports:
  #     - "5555:5555"
  #   restart: unless-stopped

  # Enable to use RabbitMQ
  # rabbitmq:
  #   container_name: mayan-edms-rabbitmq
  #   image: healthcheck/rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: mayan
  #     RABBITMQ_DEFAULT_PASS: mayanrabbitpass
  #     RABBITMQ_DEFAULT_VHOST: mayan
  #   networks:
  #     - mayan-bridge
  #   restart: unless-stopped
  #   volumes:
  #     - /docker-volumes/mayan-edms/rabbitmq:/var/lib/rabbitmq

  # Enable to run stand alone workers
  # worker_fast:
  #   command:
  #     - run_worker
  #     - fast
  #   depends_on:
  #     - postgresql
  #     - redis
  #     # Enable to use RabbitMQ
  #     # - rabbitmq
  #   environment:
  #     <<: *mayan_env
  #   image: mayanedms/mayanedms:3.2.6
  #   networks:
  #     - mayan-bridge
  #   restart: unless-stopped
  #   volumes:
  #     - /docker-volumes/mayan-edms/media:/var/lib/mayan

  # Enable to run stand frontend gunicorn
  # frontend:
  #   command:
  #     - run_frontend
  #   depends_on:
  #     - postgresql
  #     - redis
  #     # Enable to use RabbitMQ
  #     # - rabbitmq
  #   environment:
  #     <<: *mayan_env
  #   image: mayanedms/mayanedms:3.2.6
  #   networks:
  #     - mayan-bridge
  #   ports:
  #     - "81:8000"
  #   restart: unless-stopped
  #   volumes:
  #     - /docker-volumes/mayan-edms/media:/var/lib/mayan
